### ISSUE TITLE
Prompts can not be meaningfully rendered in non-TTY environments

### ISSUE THREAD

**Issue by brianjquinn** [yeoman/yeoman-test#78]
yeoman-test@2.2.0
yeoman-generator@4.6.0

Out of no where yesterday, my yeoman generator's unit tests using this yeoman-test `run()` function is suddenly failing with:

```
(node:6088) UnhandledPromiseRejectionWarning: Error: Prompts can not be meaningfully rendered in non-TTY environments
    at TestAdapter.promptModule (<redacted>/node_modules/inquirer/lib/inquirer.js:30:27)
    at TestAdapter.prompt (<redacted>/node_modules/yeoman-test/lib/adapter.js:78:22)
...
```

My test looks something like this:
```javascript
const helpers = require('yeoman-test');
const generator = path.join(__dirname, '../generators/app');
const RunContext = helpers.run(generator).withPrompts({ ... }).withOptions({skipInstall: false}).inDir(path.join(__dirname, 'temp');
```

The above stack trace happens both in my build (Jenkins) and when run locally on the command line.

**Comment by mshima** [comment]
Inquirer.js has released version 7.0.5.
That seems to be the root cause.
You should consider a package lock file for now.

**Comment by brianjquinn** [comment]
Could you elaborate how a package-lock on my side would alleviate the issue? How would I force this package not to pull in the latest version of inquirer when you are using the semver string "^7.0.0"?

**Comment by mshima** [comment]
This problem was caused by https://github.com/SBoudrias/Inquirer.js/pull/891
This PR should fix the problem https://github.com/SBoudrias/Inquirer.js/pull/896

I analyzed the bug and it’s not fixable on yeoman-test.
It requires a new inquirer release.
Closing since we have to wait for an upstream fix.

**Comment by SBoudrias** [comment]
A new release has been pushed to npm. Let me know if that's still a problem!

**Comment by tuckbick** [comment]
This doesn't seemed to have helped my case where I've provided prompt answers via `withPrompts({...})`. The `isTTY` check put into place in `fetchAnswer()` will run regardless of whether or not prompt answers have been provided.

**Comment by brianjquinn** [comment]
@SBoudrias - My use case is identical to @tuckbick's and I also still experience the error quoted in this issue post updating to the latest npm release of inquirer (which I believe is 7.0.6)

**Comment by mshima** [comment]
There is a PR to fix this issue https://github.com/SBoudrias/Inquirer.js/pull/903
